// src/pptx/pptxGenerator.js
import officegen from "officegen";

export const generatePptx = (cardTitle, data) => {
    const pptx = officegen("pptx");

    // エラーハンドリング
    pptx.on("error", (err) => {
        console.log(err);
    });

    // スライド1枚目
    const slide1 = pptx.makeTitleSlide(cardTitle, "Generated by Tongullman");
    slide1.name = "Title Slide";

    // スライド2枚目
    const slide2 = pptx.makeNewSlide();
    slide2.name = "Table of Contents";
    slide2.addText("目次", { x: "50%", y: 0, fontSize: 36, align: "center" });

    const tableOfContents = data.map((item) => item.listName);
    slide2.addText(tableOfContents.join("\n"), { x: "50%", y: "15%", fontSize: 24, align: "center" });

    // スライド3枚目以降
    data.forEach((list) => {
        const listSlide = pptx.makeTitleSlide(list.listName);
        listSlide.name = list.listName;
        list.cards.forEach((card) => {
            const slide = pptx.makeNewSlide();
            slide.name = card.title;
            slide.addText(card.title, { x: "50%", y: 0, fontSize: 36, align: "center" });
            slide.addText(card.description.split("\n").join("\n\n"), { x: "5%", y: "15%", fontSize: 24 });
        });
    });
    // PPTXファイルをダウンロード
    pptx.generate((err, stream) => {
        if (err) {
            console.log(err);
            return;
        }

        const blob = new Blob([stream], { type: "application/vnd.openxmlformats-officedocument.presentationml.presentation" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = "output.pptx";
        a.click();
        URL.revokeObjectURL(url);
    });

    console.log("PowerPoint file created: output.pptx");
};
